### ISSUE TITLE
一些小bug

### ISSUE THREAD

**Issue by ERRIC729** [888xc888/GAN_pytorch#1]
在训练时候提示张量不太对，有什么解决的方法么大佬
![image](https://github.com/user-attachments/assets/e486931b-ddf0-4e2c-b6ce-a696cc2ae11a)

**Comment by XuChen-AI** [comment]
我记得我当时跑起来了，效果很差而已，emmm检查一下输入图片的尺寸啥的，希望可以对你有帮助。
 我这个代码写的有点草率的，不一定对，这种bug可以试着问一下ai，vscode的插件ai，通义、豆包的ai都定好用，有条件的话用copilot，祝你完美的解决你的问题，加油。
  【ps：我记得我当时这段DCGAN代码 90%是ai生成的，自己稍微调整了一下就】

> 在训练时候提示张量不太对，有什么解决的方法么大佬 ![image](https://private-user-images.githubusercontent.com/162078861/393758207-e486931b-ddf0-4e2c-b6ce-a696cc2ae11a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3MzM4NzAsIm5iZiI6MTczMzczMzU3MCwicGF0aCI6Ii8xNjIwNzg4NjEvMzkzNzU4MjA3LWU0ODY5MzFiLWRkZjAtNGUyYy1iNmNlLWE2OTZjYzJhZTExYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIwOVQwODM5MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xODRhODFmOTQwNTA4OGE2NjAyZjllYTIxZTY1ODkyNTE0NmVjZDljNzI3NWY2ZWFmYzliM2YzMDdkZWNjYmU3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.2iMZ13_4vK9jPkqki9sc_b3wTnI0fwgCV1zscQttQJA)
